### ISSUE TITLE
Homepage overflows horizontally

### ISSUE THREAD

**Issue by yugabe** [dotnet-presentations/dotnetconf2018#2]
When registering a local event, I came across this issue on the event's official site.
The https://www.dotnetconf.net/ site overflows horizontally with content, because of the video item at the top of the page (it's different how badly in different browsers).
The quickest way to fix it (it seems) is to add this CSS:
```CSS
#videoWrapper {
  overflow-x: hidden;
}

**Comment by BethMassi** [comment]
@yugabe sorry for the slow reply. Thanks for this. @jglozano is looking at it.

**Comment by BethMassi** [comment]
I think we finally fixed this :-)
