### ISSUE TITLE
Error opening What's new in ASP.NET Core.pptx

### ISSUE THREAD

**Issue by TylerReid** [dotnet-presentations/dotnetconf2018#5]
I am able to open [this presentation](https://github.com/dotnet-presentations/dotnetconf2018/blob/master/Technical/Decks/Whats%20Coming%20to%20Csharp.pptx) but [this pptx](https://github.com/dotnet-presentations/dotnetconf2018/blob/master/Technical/Decks/What's%20new%20in%20ASP.NET%20Core.pptx) can't be opened with the following error:

![image](https://user-images.githubusercontent.com/2939992/45450396-210b1180-b6a6-11e8-9380-1e84ffc1cd78.png)

**Comment by nour-s** [comment]
Same here.

**Comment by estiller** [comment]
Me too.

**Comment by amaldevv** [comment]
Me too

**Comment by BethMassi** [comment]
I think I fixed this. Can you check?

**Comment by estiller** [comment]
Yep. Works now! Thanks 😄
