### ISSUE TITLE
Error opening .NET Core Microservice Development Made Easy with Azure Dev Spaces.pptx

### ISSUE THREAD

**Issue by lqdev** [dotnet-presentations/dotnetconf2018#8]
![image](https://user-images.githubusercontent.com/11130940/45523617-42e4c100-b798-11e8-9098-833ba2275e6b.png)

Not authorized to open the presentation.

**Comment by takekazuomi** [comment]
I have same issue.

**Comment by nour-s** [comment]
Same here.

**Comment by FreeAndNil** [comment]
Same with Blazor_Modern Web development with .NET and WebAssembly.pptx

**Comment by som-nitjsr** [comment]
they are protected by rights management. please remove that

**Comment by huanlin** [comment]
Same with "Entity Framework Core 2.2 and beyond.pptx"

**Comment by BethMassi** [comment]
Sorry for the delay, folks. I've been asleep since the conference ended Friday evening ;-)

I went throuch all the decks and I think I've fixed them all.
