### ISSUE TITLE
Error opening Azure Durable Functions for Serverless .NET Orchestration.pptx

### ISSUE THREAD

**Issue by arnaudmaichac** [dotnet-presentations/dotnetconf2018#9]
![45523617-42e4c100-b798-11e8-9098-833ba2275e6b](https://user-images.githubusercontent.com/15351380/45596121-f75c2e00-b9b6-11e8-83a6-126164c0418a.png)

Seems we are not authorized to open the presentation.

**Comment by yaronzo** [comment]
I have the same problem with the most of the PPTXs 👎

**Comment by BethMassi** [comment]
Can you see if it's working now?

**Comment by arnaudmaichac** [comment]
@BethMassi it works now, thanks!
